#!/usr/bin/env zsh

# We're not caring about uniq-ing entries, as we're assuming the following
# command was executed earlier in the shell's history:
#   typeset -gU path

# Reverse iterate the array
# Sources:
# https://unix.stackexchange.com/questions/27382/how-do-i-reverse-a-for-loop
# https://github.com/grml/zsh-lovers/blob/master/zsh-lovers.1.txt
for dir in ${(Oa)argv}; do
  if [ -d "$dir" ]; then
    path=( $dir $path )
  fi
done

# for debugging
#print -R $path
