#!/bin/sh

# If this command exists, don't define the function
if hash watch 2>/dev/null; then
  return 0
fi

watch () {
  local usage
  usage() {
    echo "Usage: $0 [ -i interval ] command ..."
    echo "  interval: interval between executions, in seconds"
    return 1
  }

  # default interval is 1 second
  interval=1

  while getopts "i:" opt; do
    case $opt in
      i)
        interval=$OPTARG
        ;;

      \?)
        usage
        return 1
        ;;
      :)
        echo "Option -$OPTARG requires an argument." >&2
        usage
        return 1
        ;;
    esac
  done

  shift $((OPTIND-1))

  while true; do
    clear
    echo "Watching ($interval secs.) command: " "$@"
    eval "$@"
    sleep $interval
  done
}

