#!/bin/sh

# rc => interactive shells (usually (on macOS at least) they're also login shells)
# profile => login shell (this is where we want to put most env var setting)

SHELL_RESOURCES=~/.shells

# All code here should be POSIX-compliant. We can switch on $0 to use other
# features, though.

# Global vars to be used during init, and undeffed at the end of this file
uname_s=$(uname -s)

# Define basic functions for each shell
if [ ! -z "$ZSH_VERSION" ]; then
  # echo "zsh funcs!"
  # For now, no need to include compat.sh
  . ${SHELL_RESOURCES}/compat.zsh
else
  case ${0} in
    # git-bash will have $0 as /usr/bin/bash
    -sh|sh|-ash|ash|-dash|dash|-bash|bash|*/bash)
      # echo "(ba)sh funcs!"
      . ${SHELL_RESOURCES}/compat.sh
      ;;
    *)
      echo uh oh... Don\'t know about this shell: ${0}
      echo this is not going to go well...
      env
      ;;
  esac
fi


# load general files (used for sh, bash, and zsh)
for rc in ${SHELL_RESOURCES}/rc.*; do
  . ${rc}
done

unset uname_s

FILCAB_SHELL_INIT=yes
