#!/bin/bash

# Copyright (c) 2010 by Filipe Cabecinhas
# Aliases and functions to be used only on Darwin (Mac OS X) systems

if [ "`uname -s`" == "Darwin" ];
then

function _itunes()
{
  local cur prev iTunes_cmds
  COMPREPLY=()
  iTunes_cmds=`itunes --commands`
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  COMPREPLY=( $(compgen -W "${iTunes_cmds}" -- "${cur}" ) )
  return 0
}

complete -F _itunes itunes

fi # `uname -s` == Darwin

